openapi: 3.0.0
info:
  title: Papahana_demo
  description: WMKO API to the Observation Management System
  contact:
    email: observing-support@keck.hawaii.edu
  license:
    name: BSD 3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  version: "0.1"
servers:
- url: http://localhost:8080/v0
tags:
- name: Instrument
  externalDocs:
    description: Find out more
    url: https://keckobservatory.atlassian.net/wiki/spaces/DSI/pages/808779858/Programmatic+Web+Interfacej
- name: Semester ID
  externalDocs:
    description: Find out more
    url: https://keckobservatory.atlassian.net/wiki/spaces/DSI/pages/808779858/Programmatic+Web+Interfacej
- name: Containers
  externalDocs:
    description: Find out more
    url: https://keckobservatory.atlassian.net/wiki/spaces/DSI/pages/808779858/Programmatic+Web+Interfacej
- name: Templates
  externalDocs:
    description: Find out more
    url: https://keckobservatory.atlassian.net/wiki/spaces/DSI/pages/808779858/Programmatic+Web+Interfacej
- name: Observation Block
  externalDocs:
    description: Find out more
    url: https://keckobservatory.atlassian.net/wiki/spaces/DSI/pages/808779858/Programmatic+Web+Interfacej

paths:
  /semesterIds/:
    summary: Retrieves all the sem_ids associated with an observer
    get:
      tags:
        - Semester Id
      summary: retrieves all the sem_ids associated with an observer.
      operationId: sem_id_get
      parameters:
        - $ref: '#/components/parameters/obs_id'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "400":
          description: Invalid status value
        "401":
          description: Unauthorized
        "404":
          description: Observation Id not found.
      x-swagger-router-controller: SemesterId
      x-openapi-router-controller: papahana.controllers.semester_id_controller
  /semesterIds/{semester}/semester/:
    summary: retrieves sem_id of a given semester for an obs_id.
    get:
      tags:
        - Semester Id
      summary: retrieves all the sem_id associated with an observer for the semester.
      operationId: sem_id_semester_get
      parameters:
        - $ref: '#/components/parameters/semester_path'
        - $ref: '#/components/parameters/obs_id'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "400":
          description: Invalid status value
        "401":
          description: Unauthorized
        "404":
          description: Observation or Semester ID not found.
      x-swagger-router-controller: SemesterId
      x-openapi-router-controller: papahana.controllers.semester_id_controller
  /semesterIds/{sem_id}/ob:
    summary: retrieve the ob_block information of a given semester ID.
    get:
      tags:
        - Semester Id
      summary: Retrieves the ob_blocks for a sem_id.
      operationId: sem_id_ob_get
      parameters:
        - $ref: '#/components/parameters/sem_id'
        - $ref: '#/components/parameters/obs_id'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ObservationBlock'
        "400":
          description: Invalid status value
        "401":
          description: Unauthorized
        "404":
          description: Observation or Semester ID not found
      x-swagger-router-controller: SemesterId
      x-openapi-router-controller: papahana.controllers.semester_id_controller
  /semesterIds/{sem_id}/proposal:
    get:
      tags:
        - Semester Id
      description: retrieves the proposal associated with the program.
      operationId: sem_id_proposal_get
      parameters:
        - $ref: '#/components/parameters/sem_id'
        - $ref: '#/components/parameters/obs_id'
      responses:
        "200":
          description: returns the pdf or ps file of the proposal.
          content:
            application/pdf:
              schema:
                type: string
        "400":
          description: Invalid status value
        "401":
          description: Unauthorized
        "404":
          description: Program not found.
      x-swagger-router-controller: SemesterId
      x-openapi-router-controller: papahana.controllers.semester_id_controller
  /semesterIds/{sem_id}/targets:
    get:
      tags:
        - Semester Id
      description: Retrieves all the targets associated with a program.
      operationId: sem_id_targets_get
      parameters:
        - $ref: '#/components/parameters/sem_id'
        - $ref: '#/components/parameters/obs_id'
      responses:
        "200":
          description: array of targets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Target'
        "400":
          description: Invalid status value
        "401":
          description: Unauthorized
        "404":
          description: Program not found.
      x-swagger-router-controller: SemesterId
      x-openapi-router-controller: papahana.controllers.semester_id_controller
  /semesterIds/{sem_id}/containers:
    get:
      tags:
        - Containers
        - Semester Id
      description: Retrieves all containers associated with a program
      operationId: sem_id_containers_get
      parameters:
        - $ref: '#/components/parameters/sem_id'
        - $ref: '#/components/parameters/obs_id'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Container'
        "400":
          description: Invalid status value
        "401":
          description: Unauthorized
        "404":
          description: Container not found
      x-swagger-router-controller: SemesterId
      x-openapi-router-controller: papahana.controllers.semester_id_controller
  /semesterIds/{sem_id}/submit:
    post:
      tags:
        - Semester Id
      description: Submits a program (OBs).  Uses the obsid in the authentication \
                    header and provided semId to retrieve the proposal file \
                    associated with the program
      operationId: sem_id_submit_post
      parameters:
        - $ref: '#/components/parameters/sem_id'
        - $ref: '#/components/parameters/obs_id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObservationBlock'
        required: true
      responses:
        "201":
          description: OK, new program created.
        "400":
          description: Invalid status value
        "401":
          description: Unauthorized
        "404":
          description: Observation ID not found.
      x-swagger-router-controller: SemesterId
      x-openapi-router-controller: papahana.controllers.semester_id_controller

    put:
      tags:
        - Semester Id
      description: updates a program (OBs)
      operationId: sem_id_submit_put
      parameters:
        - $ref: '#/components/parameters/sem_id'
        - $ref: '#/components/parameters/obs_id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObservationBlock'
      responses:
        "200":
          description: List of objects added to the program
        "400":
          description: Invalid status value
        "401":
          description: Unauthorized
        "404":
          description: Observation ID not found.
      x-swagger-router-controller: SemesterId
      x-openapi-router-controller: papahana.controllers.semester_id_controller

  /containers:
    get:
      tags:
        - Containers
      description: Retrieves a specific container's information
      operationId: containers_get
      parameters:
        - $ref: '#/components/parameters/container_id'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Container'
        "400":
          description: Invalid status value
        "401":
          description: Unauthorized
        "404":
          description: Container not found
      x-swagger-router-controller: Containers
      x-openapi-router-controller: papahana.controllers.containers_controller
    put:
      tags:
        - Containers
      description: Overwrites a container
      operationId: containers_put
      parameters:
        - $ref: '#/components/parameters/container_id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Container'
        required: true
      responses:
        "201":
          description: OK
        "401":
          description: Unauthorized
        "404":
          description: Container id not found
      x-swagger-router-controller: Containers
      x-openapi-router-controller: papahana.controllers.containers_controller
    post:
      tags:
        - Containers
      description: Creates a container
      operationId: containers_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Container'
        required: true
      responses:
        "201":
          description: OK
        "401":
          description: Unauthorized
        "404":
          description: Container id not found
      x-swagger-router-controller: Containers
      x-openapi-router-controller: papahana.controllers.containers_controller
    delete:
      tags:
        - Containers
      description: Delete container by id
      operationId: containers_delete
      parameters:
        - $ref: '#/components/parameters/container_id'
      responses:
        "204":
          description: Deleted
        "401":
          description: Unauthorized
        "404":
          description: Container id not found
      x-swagger-router-controller: Containers
      x-openapi-router-controller: papahana.controllers.containers_controller
  /containers/append:
    put:
      tags:
      - Containers
      description: Appends an observation block to a container by id
      operationId: containers_append_put
      parameters:
        - $ref: '#/components/parameters/container_id'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
        required: true
      responses:
        "201":
          description: OK
        "400":
          description: Invalid status value
        "401":
          description: Unauthorized
        "404":
          description: Container not found
      x-swagger-router-controller: Containers
      x-openapi-router-controller: papahana.controllers.containers_controller
  /containers/executionTimes:
    get:
      tags:
      - Containers
      description: Calculate the total execution time of a container
      operationId: containers_execution_times_get
      parameters:
        - $ref: '#/components/parameters/container_id'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: number
                description: miliseconds
                x-content-type: application/json
        "400":
          description: Invalid status value
        "401":
          description: Unauthorized
        "404":
          description: Container not found
      x-swagger-router-controller: Containers
      x-openapi-router-controller: papahana.controllers.containers_controller
  /containers/items:
    get:
      tags:
      - Containers
      description: Retrieves the ordered list of observing blocks in a container
      operationId: containers_items_get
      parameters:
        - $ref: '#/components/parameters/container_id'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ObservationBlock'
                x-content-type: application/json
        "400":
          description: Invalid status value
        "401":
          description: Unauthorized
        "404":
          description: Container not found
      x-swagger-router-controller: Containers
      x-openapi-router-controller: papahana.controllers.containers_controller
  /containers/items/summary:
    get:
      tags:
      - Containers
      description: Retrieves a summary of container information
      operationId: containers_items_summary_get
      parameters:
        - $ref: '#/components/parameters/container_id'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Container'
        "400":
          description: Invalid status value
        "401":
          description: Unauthorized
        "404":
          description: Container not found
      x-swagger-router-controller: Containers
      x-openapi-router-controller: papahana.controllers.containers_controller
  /containers/verify:
    get:
      tags:
      - Containers
      description: Request verification of the elements of a container. Sends container summary
        as a sucessfull response
      operationId: containers_verify_get
      parameters:
        - $ref: '#/components/parameters/container_id'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Container'
        "400":
          description: Invalid status value
        "401":
          description: Unauthorized
        "404":
          description: Container not found
      x-swagger-router-controller: Containers
      x-openapi-router-controller: papahana.controllers.containers_controller
  /containers/scheduleToO:
    post:
      tags:
      - Containers
      description: Submits a container for Target of Opportunity (ToO) (all the elements)
      operationId: containers_schedule_too_post
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Container'
        required: true
      responses:
        "200":
          description: OK
        "400":
          description: Invalid status value
        "401":
          description: Unauthorized
        "404":
          description: Container not found
      x-swagger-router-controller: Containers
      x-openapi-router-controller: papahana.controllers.containers_controller
  /containers/export:
    get:
      tags:
      - Containers
      description: Retrieves a specific container information in a file format (default
        .json)
      operationId: containers_export_get
      parameters:
        - $ref: '#/components/parameters/container_id'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Container'
        "400":
          description: Invalid status value
        "404":
          description: Container not found
      x-swagger-router-controller: Containers
      x-openapi-router-controller: papahana.controllers.containers_controller

  /instrumentPackages/{instrument}:
    get:
      tags:
      - Instrument
      description: Retrieves the the available instrument packages for an instrument.
      operationId: instrument_packages
      parameters:
      - $ref: '#/components/parameters/instrument'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentPackage'
        "400":
          description: Invalid status value
        "404":
          description: Group not found
      x-swagger-router-controller: Instrument
      x-openapi-router-controller: papahana.controllers.instrument_controller
  /instrumentPackages/{instrument}/{ip_version}/parameters:
    get:
      tags:
      - Instrument
      description: List all template parameters that can be attached to OBs using
        this instrument package
      operationId: instrument_packages_ip_parameter
      parameters:
      - $ref: '#/components/parameters/instrument'
      - $ref: '#/components/parameters/ip_version'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentPackage'
        "400":
          description: Invalid status value
        "404":
          description: Group not found
      x-swagger-router-controller: Instrument
      x-openapi-router-controller: papahana.controllers.instrument_controller
  /instrumentPackages/{instrument}/{ip_version}/{template_name}:
    get:
      tags:
      - Instrument
      - Templates
      description: Retrieves the specified instrument package template parameters
      operationId: instrument_packages_ip_template
      parameters:
      - $ref: '#/components/parameters/instrument'
      - $ref: '#/components/parameters/ip_version'
      - $ref: '#/components/parameters/template_name'

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentPackage'
        "400":
          description: Invalid status value
        "404":
          description: Group not found
      x-swagger-router-controller: Instrument
      x-openapi-router-controller: papahana.controllers.instrument_controller

  /obsBlocks:
    get:
      tags:
      - Observation Block
      description: "Retrieves the general parameters of an OB (target, exec time, other as needed)"
      operationId: ob_get
      parameters:
        - $ref: '#/components/parameters/ob_id'
      responses:
        "200":
          description: On success gets a new OB.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObservationBlock'
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
    put:
      tags:
      - Observation Block
      description: Updates the observation block with the new one
      operationId: ob_put
      parameters:
        - $ref: '#/components/parameters/ob_id'
      requestBody:
        description: Observation block replacing ob_id.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObservationBlock'
        required: true
      responses:
        "200":
          description: On a success replaces the given OB with the updated OB.
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
    post:
      tags:
      - Observation Block
      description: Inserts an observation block.
      operationId: ob_post
      requestBody:
        description: Observation block to be added.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObservationBlock'
        required: true
      responses:
        "200":
          description: On a success inserts new OB.
          content:
            application/json:
              schema:
                type: string
                description: id of new ob.
                x-content-type: application/json
        "400":
          description: Invalid status value
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
    delete:
      tags:
      - Observation Block
      description: Removes the observation block
      operationId: ob_delete
      parameters:
        - $ref: '#/components/parameters/ob_id'
      responses:
        "200":
          description: On a success removes given OB from the database.
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
  /obsBlocks/template:
    get:
      tags:
        - Observation Block
      description: Retrieves the list of templates associated with the OB
      operationId: ob_template_get
      parameters:
        - $ref: '#/components/parameters/ob_id'
      responses:
        "200":
          description: On success Returns the Target and Metadata of the observing block being requested.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TemplateSchema'
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
    post:
      tags:
        - Observation Block
      description: Creates the list of templates associated with the OB
      operationId: ob_template_post
      parameters:
        - $ref: '#/components/parameters/ob_id'
        - $ref: '#/components/parameters/template_type'
      requestBody:
        content:
          application/json:
            schema:
                oneOf:
                  - $ref: '#/components/schemas/TemplateSchema'
                  - type: array
                    items:
                      $ref: '#/components/schemas/TemplateSchema'
        required: true
      responses:
        "200":
          description: On success inserts a new list of templates associated with the OB.
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
    put:
      tags:
        - Observation Block
      description: Updates the list of templates associated with the OB
      operationId: ob_template_put
      parameters:
        - $ref: '#/components/parameters/ob_id'
        - $ref: '#/components/parameters/template_type'
      requestBody:
        content:
          application/json:
            schema:
                oneOf:
                  - $ref: '#/components/schemas/TemplateSchema'
                  - type: array
                    items:
                      $ref: '#/components/schemas/TemplateSchema'

        required: true
      responses:
        "200":
          description: On success replaces the given templates with new list of templates.
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
  /obsBlocks/template/{template_id}:
    get:
      tags:
        - Observation Block
      description: Retrieves the specified template within the OB
      operationId: ob_template_id_get
      parameters:
        - $ref: '#/components/parameters/ob_id'
        - $ref: '#/components/parameters/template_id'
      responses:
        "200":
          description: Retrieves and returns the Template of the observing block being requested
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemplateSchema'
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
    put:
      tags:
        - Observation Block
      description: Updates the specified template within the OB
      operationId: ob_template_id_put
      parameters:
        - $ref: '#/components/parameters/ob_id'
        - $ref: '#/components/parameters/template_id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemplateSchema'
        required: true
      responses:
        "200":
          description: replaces the given Template within the OB with Template of id=templateId
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
    delete:
      tags:
        - Observation Block
      description: Removes the specified template within the OB
      operationId: ob_template_id_delete
      parameters:
        - $ref: '#/components/parameters/ob_id'
        - $ref: '#/components/parameters/template_id'
      responses:
        "200":
          description: removes the template from the OB
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
  /obsBlocks/template/{template_id}/{file_parameter}:
    get:
      tags:
        - Observation Block
      description: Retrieves the specified template within the OB
      operationId: ob_template_id_file_get
      parameters:
        - $ref: '#/components/parameters/ob_id'
        - $ref: '#/components/parameters/template_id'
        - $ref: '#/components/parameters/file_parameter'
      responses:
        "200":
          description: Retrieves and returns the Template of the observing block being requested
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemplateSchema'
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
    put:
      tags:
        - Observation Block
      description: Updates the specified template within the OB
      operationId: ob_template_id_file_put
      parameters:
        - $ref: '#/components/parameters/ob_id'
        - $ref: '#/components/parameters/template_id'
        - $ref: '#/components/parameters/file_parameter'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              format: binary
        required: true
      responses:
        "200":
          description: replaces the given Template within the OB with Template of id=templateId
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
  /obsBlocks/template/duplicate/{template_id}:
    post:
      tags:
        - Observation Block
      description: Generate a new copy of the template and add it to the list of templates in the OB.
      operationId: ob_template_duplicate
      parameters:
        - $ref: '#/components/parameters/ob_id'
        - $ref: '#/components/parameters/template_id'
      responses:
        "200":
          description: returns a copy of the Template within the OB.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemplateSchema'
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
  /obsBlocks/completelyFilledIn:
    get:
      tags:
        - Observation Block
      description: Verify that the required parameters have been filled in.
      operationId: ob_template_filled
      parameters:
        - $ref: '#/components/parameters/ob_id'
      responses:
        "200":
          description: On success returns True.
          content:
            application/json:
              schema:
                type: boolean
                x-content-type: application/json
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
        "422":
          description: OB is missing required parameters.
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
  /obsBlocks/supplementFiles:
    get:
      tags:
        - Observation Block
      description: Retrieves list of files.
      operationId: ob_template_supplement
      parameters:
        - $ref: '#/components/parameters/ob_id'
      responses:
        "200":
          description: On success gets list of files associated with the OB.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                x-content-type: application/json
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
  /obsBlocks/timeConstraints:
    get:
      tags:
        - Observation Block
      description: Retrieves the time constraints (from, to).
      operationId: ob_time_constraint_get
      parameters:
        - $ref: '#/components/parameters/ob_id'
      responses:
        "200":
          description: On success retrieves a list of existing time constraint(s) of an OB.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                x-content-type: application/json
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
    put:
      tags:
        - Observation Block
      description: Creates / Replaces the time constraints (from, to).
      operationId: ob_time_constraint_put
      parameters:
        - $ref: '#/components/parameters/ob_id'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
        required: true
      responses:
        "200":
          description: On success updates an existing time constraint(s) of an OB.
        "400":
          description: Invalid input time constraints -- input must be an array.
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
  /obsBlocks/schedule:
    get:
      tags:
        - Observation Block
      description: Retrieves scheduling information.
      operationId: ob_schedule_get
      parameters:
        - $ref: '#/components/parameters/ob_id'
      responses:
        "200":
          description: On success retrieves the existing ob schedule,  a list of dates.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                x-content-type: application/json
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
    put:
      tags:
        - Observation Block
      description: On success updates an existing ob schedule.
      operationId: ob_schedule_put
      parameters:
        - $ref: '#/components/parameters/ob_id'
      responses:
        "200":
          description: On success updates an existing time constraint(s) of an OB.
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
  /obsBlocks/executions:
    get:
      tags:
        - Observation Block
      description: Retrieves the list of execution attempts for a specific OB (for a specific night).
      operationId: ob_executions
      parameters:
        - $ref: '#/components/parameters/ob_id'
      responses:
        "200":
          description: On success retrieves a list of execution attempts of an OB.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                x-content-type: application/json
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
  /obsBlocks/executionTime:
    get:
      tags:
        - Observation Block
      description: Calculates the execution time.
      operationId: ob_execution_time
      parameters:
        - $ref: '#/components/parameters/ob_id'
      responses:
        "200":
          description: On success returns an estimated execution time for an OB.
          content:
            application/json:
              schema:
                type: number
                x-content-type: application/json
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
  /obsBlocks/duplicate:
    post:
      tags:
        - Observation Block
      description: Duplicate the OB, default is current semId.
      operationId: ob_duplicate
      parameters:
        - $ref: '#/components/parameters/ob_id'
        - $ref: '#/components/parameters/sem_id_not_required'
      responses:
        "200":
          description: On success a new OB is generated, with a new unique ID. If needed the OB is associated with a new semester.
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
  /obsBlocks/upgrade:
    post:
      tags:
        - Observation Block
      description: When an instrument package changes, attempts to port an existing OB to the new package, default is the current semId.
      operationId: ob_upgrade
      parameters:
        - $ref: '#/components/parameters/ob_id'
      responses:
        "200":
          description: On success the new version of the OB is returned, with a new unique ID.  If the upgrade fails (the New OB must pass verification), an error code is generated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObservationBlock'
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller
  /obsBlocks/export:
    get:
      tags:
        - Observation Block
      description: Exports an OB in human-readable format.
      operationId: ob_export
      parameters:
        - $ref: '#/components/parameters/ob_id'
      responses:
        "200":
          description: On success a TBD text version of the OB is returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObservationBlock'
        "400":
          description: Invalid status value
        "404":
          description: Observation Block not found
      x-swagger-router-controller: Observation
      x-openapi-router-controller: papahana.controllers.observation_block_controller

components:
  schemas:
    Container:
      required:
        - name
        - sem_id
        - observation_blocks
      type: object
      properties:
        name:
          type: string
        sem_id:
          $ref: '#/components/schemas/SemIdSchema'
        observation_blocks:
          type: array
          items:
            type: string
          default: []
        comment:
          type: string

    ObservationBlock:
      required:
        - metadata
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/ObsBlockMetadata'
        target:
          items:
            $ref: '#/components/schemas/Target'
        acquisition:
          $ref: '#/components/schemas/Acquisition'
        science:
          type: array
          items:
            $ref: '#/components/schemas/ScienceTemplate'
        # TODO add calibration and eng templates here
        observation:
          type: array
          items:
            $ref: '#/components/schemas/ObservationTemplate'
        associations:
          type: array
          items:
            type: string
        status:
          $ref: '#/components/schemas/Status'
        time_constraints:
          type: array
          items:
            type: string
        comment:
          type: string
          example:
            A great Observation Block.

    ObsBlockMetadata:
      required:
        - name
        - version
        - ob_type
        - pi_id
        - sem_id
        - instrument
      type: object
      properties:
        name:
          type: string
        version:
          type: number
        ob_type:
          type: string
          enum:
            - science
            - calibration
            - engineering
        priority:
          type: number
        pi_id:
          type: integer
        sem_id:
          $ref: '#/components/schemas/SemIdSchema'
        instrument:
          $ref: '#/components/schemas/InstrumentEnum'
        comment:
          type: string
      example:
        name: "standard stars #9"
        version: 0.1
        pi_id: 7766
        sem_id: "2021A_U046"
        instrument: "KCWI"
        comment: "All I see are stars."

    Status:
      type: object
      properties:
        state:
          type: string
          enum:
            - started
            - executed
            - completed
            - failed
            - terminated
            - stopped
          default: started
        executions:
          type: array
          items:
            type: string
          default: []
        deleted:
          type: boolean
          default: false

    ObservationTemplate:
      # TODO this is a place holder until Eng and Cal templates are added.
      type: object
      properties:
        metadata:
          type: array
          items:
            $ref: '#/components/schemas/ObservationMetadata'
        template_index:
          $ref: '#/components/schemas/TemplateIdSchema'

    ScienceTemplate:
      required:
        - metadata
        - parameters
      type: object
      properties:
        metadata:
          type: array
          items:
            $ref: '#/components/schemas/ObservationMetadata'
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/ScienceParameters'
        template_index:
          $ref: '#/components/schemas/TemplateIdSchema'

    Acquisition:
      required:
      - metadata
      - parameters
      type: object
      properties:
        metadata:
          type: array
          items:
            $ref: '#/components/schemas/ObservationMetadata'
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/AcquisitionParameters'
        template_index:
          $ref: '#/components/schemas/TemplateIdSchema'

    ObservationMetadata:
      required:
        - name
        - ui_name
        - instrument
        - version
        - script
      type: object
      properties:
        name:
          type: string
        ui_name:
          type: string
        instrument:
          $ref: '#/components/schemas/InstrumentEnum'
        template_type:
          type: string
          enum:
            - "acquisition"
          default: "acquisition"
        version:
          type: number
        script:
          type: string
      example:
        name: KCWI_ifu_acq_offsetStar
        ui_name: KCWI direct
        instrument: KCWI
        template_type: acquisition
        version: 0.1
        script: KCWI_ifu_acq_offsetStar

    AcquisitionParameters:
      required:
        - rotmode
        - guider_po
        - guider_gs_mode
      type: object
      properties:
        wrap:
          type: string
          enum:
            - "south"
            - "north"
            - "auto"
          default: "auto"
        rotmode:
          type: string
          enum:
            - "PA"
            - "stationary"
            - "vertical_angle"
        guider_po:
          type: string
          enum:
            - "REF"
            - "IFU"
        ra_offset:
          type: number
        dec_offset:
          type: number
        guider_gs_ra:
          $ref: '#/components/schemas/CoordinateSchema'
        guider_gs_dec:
          $ref: '#/components/schemas/CoordinateSchema'
        guider_gs_mode:
          type: string
          enum:
            - "auto"
            - "operator"
            - "user"

    ScienceParameters:
      required:
        - det1_exptime
        - det1_nexp
      type: object
      properties:
        det1_exptime:
          type: number
        det1_nexp:
          type: integer
        det2_exptime:
          type: number
        det2_nexp:
          type: integer
        seq_ndither:
          type: integer
        seq_ditarray:
          type: array
          items:
            $ref: '#/components/schemas/DitherSchema'

    Target:
      required:
      - name
      - ra
      - dec
      - magnitude
      type: object
      properties:
        name:
          type: string
        ra:
          $ref: '#/components/schemas/CoordinateSchema'
        dec:
          $ref: '#/components/schemas/CoordinateSchema'
        equinox:
          type: string
          default: "J2000"
        frame:
          type: string
          default: "Fk5"
        PA:
          type: number
          default: 0.0
        pm_ra:
          type: number
          default: 0.0
        pm_dec:
          type: number
          default: 0.0
        epoch:
          type: number
          default: 2000.0
        obstime:
          type: number
        magnitude:
          $ref: '#/components/schemas/Magnitude'
        dra:
          type: number
          default: 0.0
        ddec:
          type: number
          default: 0.0
        comment:
          type: string
      example:
        name: A Stellar Galaxy
        ra: '15:01:01'
        dec: '20:00:02.2'
        equinox: J2000
        frame: Fk5
        PA: -90.0
        pm_ra: 5.96
        pm_dec: 5.6373
        obstime: 2021-04-22 15:08:04
        comment: comment
        magnitude:
          magnitude: 14.5
          band: J

    Magnitude:
      required:
      - band
      - magnitude
      type: object
      properties:
        band:
          type: string
        magnitude:
          type: number
      example:
        magnitude: 14.7
        band: K

    FindingChart:
      description: Finding chart description goes here

    # TODO add IP template description
    InstrumentPackage:
      description: Instrument package description goes here

    TemplateIdSchema:
      type: string
      oneOf:
        - pattern: '^acq\d{1}$'
        - pattern: '^acq\d{2}$'
        - pattern: '^sci\d{1}$'
        - pattern: '^sci\d{2}$'
        - pattern: '^eng\d{1}$'
        - pattern: '^eng\d{2}$'
        - pattern: '^cal\d{1}$'
        - pattern: '^cal\d{2}$'

    InstrumentEnum:
      type: string
      enum:
        - KCWI
        - DEIMOS
        - ESI
        - HIRES
        - LRIS
        - MOSFIRE
        - OSIRIS
        - NIRES
        - NIRC2
        - kcwi
        - deimos
        - esi
        - hires
        - lris
        - mosfire
        - osiris
        - nires
        - nirc2
        - DE
        - DF
        - EI
        - HI
        - KB
        - KF
        - LB
        - LR
        - MF
        - OI
        - OS
        - NR
        - NI
        - NS
        - N2
        - NC

    CoordinateSchema:
      type: string
      oneOf:
        - pattern: '^\d{2}:\d{2}:\d{2}$'
        - pattern: '^\d{2}:\d{2}:\d{2}.\d{1}$'
        - pattern: '^\d{2}:\d{2}:\d{2}.\d{2}$'

    DitherSchema:
      required:
        - ra
        - dec
        - position
        - guided
      type: object
      properties:
        ra:
          type: number
        dec:
          type: number
        position:
          type: string
          enum:
            - T
            - S
            - O
        guided:
          type: boolean

    SemIdSchema:
      type: string
      oneOf:
        - pattern: '^\d{4}A_[A-Z]{1}\d{3}$'
        - pattern: '^\d{4}B_[A-Z]{1}\d{3}$'

    TemplateSchema:
      oneOf:
          - $ref: '#/components/schemas/ObservationTemplate'
          - $ref: '#/components/schemas/ScienceTemplate'

  parameters:
    obs_id:
      name: obs_id
      in: query
      description: observer id
      required: true
      style: form
      explode: true
      schema:
        type: integer
      example: 2009
    ob_id:
      name: ob_id
      in: query
      description: observation block id
      required: true
      style: form
      explode: true
      schema:
        type: string
      example: 6042ced0afc6ecd40fe5a3dd
    semester:
      in: query
      name: semester
      description: semester
      style: form
      explode: true
      schema:
        type: string
        default: ""
      required: false
      example: 2021A
    semester_path:
      name: semester
      in: path
      description: semester id
      required: true
      style: simple
      explode: true
      schema:
        type: string
      example: 2021A
    sem_id:
      name: sem_id
      in: path
      description: semester id
      required: true
      style: simple
      explode: true
      schema:
        type: string
      example: 2021A_U456
    sem_id_in_query:
      in: query
      name: sem_id
      description: semester id
      required: true
      explode: true
      schema:
        type: string
      example: 2021A
    sem_id_not_required:
      in: query
      name: sem_id
      description: program id including semester
      style: form
      explode: true
      schema:
        type: string
        default: ""
      required: false
      example: 2021A_U456
    template_type:
      in: query
      name: template_type
      description: A string to indicate template,  (acquisition, science, engineering, calibration)
      required: true
      explode: true
      schema:
        type: string
        enum:
        - acquisition
        - science
        - engineering
        - calibration
      example: science
    instrument:
      name: instrument
      in: path
      description: instrument used to make observation
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/InstrumentEnum'
    ip_version:
      name: ip_version
      in: path
      description: ip version description here
      required: true
      style: simple
      explode: false
      schema:
        type: number
      example: 0
    index:
      name: index
      in: path
      description: Finding chart index
      required: true
      style: simple
      explode: false
      schema:
        type: integer
      example: 0
    template_id:
      name: template_id
      in: path
      description: index of template within the OB.
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/TemplateIdSchema'
      example: sci2
    template_name:
      name: template_name
      in: path
      description: template name description goes here
      required: true
      style: simple
      explode: false
      schema:
        type: string
      example: "1"
    pi_name:
      name: pi_name
      in: query
      description: name of primary investigator associated with the project
      required: false
      style: form
      explode: true
      schema:
        type: string
      example: Pope Pious IX
    proposal_id:
      name: proposal_id
      in: query
      description: name of primary investigator associated with the project
      required: false
      style: form
      explode: true
      schema:
        type: string
      example: 1848R
    file_parameter:
      name: file_parameter
      in: path
      description: file type
      required: true
      style: simple
      explode: false
      schema:
        type: string
        enum:
          - csv
          - json
          - html
          - txt
      example: json
    container_id:
      name: container_id
      in: query
      description: container identifier
      required: true
      explode: true
      schema:
        type: string
      example: 6042ced0afc6ecd40fe5a3dd
    file_type:
      name: file_type
      in: query
      description: type of file to return
      required: false
      style: form
      explode: true
      schema:
        type: string
      example: json
    run_id:
      name: run_id
      in: query
      description: run identifier
      required: true
      style: form
      explode: true
      schema:
        type: string
      example: 6042ced0afc6ecd40fe5a3dd
    sidereal:
      name: sidereal
      in: query
      description: tracking rate
      required: true
      style: form
      explode: false
      schema:
        type: boolean

